### ISSUE TITLE
Change default textbox border to gray instead of blue

### ISSUE THREAD

**Issue by rrojan** [devhimal/todo#2]
Blue looks out of place so please change it to gray or an appropriate color.

Or you can also find out an appropriate color using [color wheel](https://www.canva.com/colors/color-wheel/)

<img width="1330" alt="image" src="https://github.com/HimalTamang/todo/assets/59971845/a90645f4-3532-4b89-8d0d-a3df91f45d01">

**Comment by devhimal** [comment]
hello @rrojan dai, I have updated the input field color from blue to grey, hr length also changed, background color updated from black to orange-red.

<img width="925" alt="issu1" src="https://github.com/devhimal/todo/assets/80043996/84dd14b2-d3b6-4f82-9e5b-5fa3630e3565">

**Comment by rrojan** [comment]
@devhimal Great job 🚀
