### ISSUE TITLE
Remove `max-width` or set background for `.wrapper`

### ISSUE THREAD

**Issue by rrojan** [devhimal/todo#3]
<img width="1440" alt="image" src="https://github.com/HimalTamang/todo/assets/59971845/48b59c54-f50d-4a44-9633-40cd3d3d567c">
Currently there are black blocks on the left and right side of the page (because my system setting is in dark mode).

You can use another background color or set the max-width to `100vw`

**Comment by devhimal** [comment]
@rrojan dai, I have updated the background color from dark to orange-red. 

<img width="592" alt="issue2" src="https://github.com/devhimal/todo/assets/80043996/1b86cea1-7c63-4159-8f15-2ffa1b7c52bd">
