### ISSUE TITLE
Set width of `<hr>`

### ISSUE THREAD

**Issue by rrojan** [devhimal/todo#5]
Currently the hr takes up the full width of the `.wrapper` div

Small issue but maybe it could look better if we aligned the ends of the line to ends of the `.filters` and `.task` divs. Normally when we design websites we try to avoid using anything that touches the outer edges of the layout.

<img width="1366" alt="image" src="https://github.com/HimalTamang/todo/assets/59971845/5527187c-e7d5-4bc5-aa34-c4128fadd565">

**Comment by devhimal** [comment]
@rrojan dai, this has been resolved.
